name: Build DarkWolf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Convert v145 to v143
      shell: powershell
      run: |
        Get-ChildItem -Recurse *.vcxproj | ForEach-Object {
          (Get-Content $_.FullName) -replace 'v145','v143' |
          Set-Content $_.FullName
        }

    - name: Build
      run: |
        msbuild src\wolf.sln /p:Configuration=Release /p:Platform=Win32

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: DarkWolf
        path: |
          src\x64\Release\**
          src\Release\**
