name: Build DarkWolf

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Convert toolset v145 -> v143
      shell: powershell
      run: |
        Get-ChildItem -Recurse *.vcxproj | ForEach-Object {
          (Get-Content $_.FullName) -replace 'v145','v143' |
          Set-Content $_.FullName
        }

    - name: Build projects
      shell: cmd
      run: |
        msbuild src\botlib\botlib.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

        msbuild src\renderer\renderer.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

        msbuild src\cgame\cgame.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

        msbuild src\ui\ui.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

        msbuild src\game\game.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

        msbuild src\wolf\wolf.vcxproj /p:Configuration=Release /p:Platform=x64
        if errorlevel 1 exit /b 1

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DarkWolf
        path: |
          src\x64\Release\**
          src\Release\**
